version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - kafka-net

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kafka-net

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kafka-net

  mongo-express:
    image: mongo-express:1.0.0
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - kafka-net

  service-registry:
    build:
      context: ./serviceRegistry
    container_name: serviceRegistry
    ports:
      - "8761:8761"
    networks:
      - kafka-net

  ticket-processing-service:
    build:
      context: ./ticket-processing-service
    container_name: ticket-processing-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - redis
      - mongo
      - serviceRegistry
    networks:
      - kafka-net

  ticket-service:
    build:
      context: ./ticket-service
    container_name: ticket-service
    ports:
      - "8089:8089"
    depends_on:
      - kafka
      - serviceRegistry
    networks:
      - kafka-net

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - serviceRegistry
    networks:
      - kafka-net

  # gatewayapi:
  #   build:
  #     context: ./gatewayapi
  #   container_name: gatewayapi
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - serviceRegistry
  #   networks:
  #     - kafka-net

volumes:
  redis_data:
  mongo_data:

networks:
  kafka-net:
    driver: bridge
