spring:
  application:
    name: ticket-processing-service

  kafka:
    bootstrap-servers: kafka:9092

  redis:
    host: redis
    port: 6379

  data:
    mongodb:
      uri: mongodb://root:example@mongo:27017/test?authSource=admin

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
