spring:
  application:
    name: ticket-service

  kafka:
    bootstrap-servers: kafka:9092

  redis:
    host: redis
    port: 6379

  data:
    mongodb:
      host: mongo
      port: 27017
      database: test

server:
  port: 8089

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka



